# Generated by Django 5.0 on 2023-12-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'Economy'), (1, 'Standard'), (2, 'Deluxe'), (3, 'Luxe')], default=1
                    ),
                ),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Occupied')], default=0)),
                ('single_beds', models.IntegerField(default=0)),
                ('double_beds', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
