# Generated by Django 5.0 on 2023-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'Economy'), (1, 'Standard'), (2, 'Deluxe'), (3, 'Luxe')], default=1
                    ),
                ),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Occupied')], default=0)),
                ('single_beds', models.IntegerField(default=0)),
                ('double_beds', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
