# Generated by Django 5.0 on 2024-01-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0002_alter_roomdata_double_beds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Кімната', 'verbose_name_plural': 'Кімнати'},
        ),
        migrations.AlterModelOptions(
            name='roomdata',
            options={'ordering': ['type'], 'verbose_name': 'Дані Кімнати', 'verbose_name_plural': 'Дані Кімнат'},
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступний'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='rooms.roomdata', verbose_name='Дані номеру'
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Free'), (1, 'Booked')], default=0, verbose_name='Статус'
            ),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='double_beds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Двоспальні ліжка'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='single_beds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Односпальні ліжка'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Economy'), (1, 'Standard'), (2, 'Deluxe'), (3, 'Luxe')], default=1, verbose_name='Тип'
            ),
        ),
    ]
